package koperasi.entity;
// Generated 15-May-2019 14:24:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Angsuran generated by hbm2java
 */
public class Angsuran  implements java.io.Serializable {


     private Integer idangsuran;
     private User user;
     private String jumlahangsuran;
     private Date tanggalangsuran;

    public Angsuran() {
    }

    public Angsuran(User user, String jumlahangsuran, Date tanggalangsuran) {
       this.user = user;
       this.jumlahangsuran = jumlahangsuran;
       this.tanggalangsuran = tanggalangsuran;
    }
   
    public Integer getIdangsuran() {
        return this.idangsuran;
    }
    
    public void setIdangsuran(Integer idangsuran) {
        this.idangsuran = idangsuran;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJumlahangsuran() {
        return this.jumlahangsuran;
    }
    
    public void setJumlahangsuran(String jumlahangsuran) {
        this.jumlahangsuran = jumlahangsuran;
    }
    public Date getTanggalangsuran() {
        return this.tanggalangsuran;
    }
    
    public void setTanggalangsuran(Date tanggalangsuran) {
        this.tanggalangsuran = tanggalangsuran;
    }




}


