package koperasi.entity;
// Generated 15-May-2019 14:24:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Laporan generated by hbm2java
 */
public class Laporan  implements java.io.Serializable {


     private Integer idlaporan;
     private String jenisLaporan;
     private Date tanggal;

    public Laporan() {
    }

    public Laporan(String jenisLaporan, Date tanggal) {
       this.jenisLaporan = jenisLaporan;
       this.tanggal = tanggal;
    }
   
    public Integer getIdlaporan() {
        return this.idlaporan;
    }
    
    public void setIdlaporan(Integer idlaporan) {
        this.idlaporan = idlaporan;
    }
    public String getJenisLaporan() {
        return this.jenisLaporan;
    }
    
    public void setJenisLaporan(String jenisLaporan) {
        this.jenisLaporan = jenisLaporan;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }




}


