package koperasi.entity;
// Generated 15-May-2019 14:24:01 by Hibernate Tools 4.3.1



/**
 * Simpanan generated by hbm2java
 */
public class Simpanan  implements java.io.Serializable {


     private Integer idsimpanan;
     private User user;
     private String jumlahsimpanan;

    public Simpanan() {
    }

    public Simpanan(User user, String jumlahsimpanan) {
       this.user = user;
       this.jumlahsimpanan = jumlahsimpanan;
    }
   
    public Integer getIdsimpanan() {
        return this.idsimpanan;
    }
    
    public void setIdsimpanan(Integer idsimpanan) {
        this.idsimpanan = idsimpanan;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getJumlahsimpanan() {
        return this.jumlahsimpanan;
    }
    
    public void setJumlahsimpanan(String jumlahsimpanan) {
        this.jumlahsimpanan = jumlahsimpanan;
    }




}


