package koperasi.entity;
// Generated 15-May-2019 14:24:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Integer idtransaksi;
     private Barang barang;
     private User user;
     private String kodeTransaksi;
     private Integer jumlahBarang;
     private String totalHarga;
     private Date tanggalTransaksi;

    public Transaksi() {
    }

    public Transaksi(Barang barang, User user, String kodeTransaksi, Integer jumlahBarang, String totalHarga, Date tanggalTransaksi) {
       this.barang = barang;
       this.user = user;
       this.kodeTransaksi = kodeTransaksi;
       this.jumlahBarang = jumlahBarang;
       this.totalHarga = totalHarga;
       this.tanggalTransaksi = tanggalTransaksi;
    }
   
    public Integer getIdtransaksi() {
        return this.idtransaksi;
    }
    
    public void setIdtransaksi(Integer idtransaksi) {
        this.idtransaksi = idtransaksi;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getKodeTransaksi() {
        return this.kodeTransaksi;
    }
    
    public void setKodeTransaksi(String kodeTransaksi) {
        this.kodeTransaksi = kodeTransaksi;
    }
    public Integer getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(Integer jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public String getTotalHarga() {
        return this.totalHarga;
    }
    
    public void setTotalHarga(String totalHarga) {
        this.totalHarga = totalHarga;
    }
    public Date getTanggalTransaksi() {
        return this.tanggalTransaksi;
    }
    
    public void setTanggalTransaksi(Date tanggalTransaksi) {
        this.tanggalTransaksi = tanggalTransaksi;
    }




}


